// Public works & permits knowledge base — the data (R25, Mike 2026-09-28).
//
// Every fact below is hand-entered from docs/research/R25_permits_lidar_pwa.md
// (verified 2026-09-28 from search snippets; city sites were unreachable, so
// phones should be dialed before they go into a customer script) or from
// src/permitting/cities.ts (verified 2026-08-01 from Mike's own permit
// correspondence). cities.ts is not edited; where it already says something,
// the fact repeats it and cites it.
//
// Rules for editing this file:
// - A fact with no source URL is UNCONFIRMED, and `notes` says why.
// - Two sources that disagree (a phone number, a rule) make ONE UNCONFIRMED
//   fact that lists both. Never pick one silently.
// - Dollar figures go in `fee` only. No price, no "clear", ever.
// - `notes` is internal. The SPSA landfill's city is named there and nowhere else.

import type { Fact } from './types.js';

const R25 = '2026-09-28';
// The date cities.ts carries. Kept as a literal on purpose: re-verifying
// cities.ts does not re-verify these copies.
const CITIES_TS = '2026-08-01';
const CITIES_TS_REF = 'arbo:src/permitting/cities.ts';

// ── Virginia Beach ──────────────────────────────────────────────────────────

const VIRGINIA_BEACH: Fact[] = [
  {
    id: 'vb-rpa-buffer',
    city: 'Virginia Beach',
    topic: 'private_tree_cbpa',
    title: 'Resource Protection Area: 100-ft buffer',
    rule:
      'Inside the Resource Protection Area (RPA) — tidal wetlands, tidal shores, connected non-tidal wetlands, plus a 100-ft vegetated buffer landward of them and along perennial streams — tree removal needs city approval. Mature trees are to be pruned instead of removed where possible, with removals kept to the fewest feasible.',
    whoToCall: { office: 'Planning Dept, Environmental Planning', phone: '757-385-6661' },
    sourceUrls: ['https://register.dls.virginia.gov/details.aspx?id=10307', 'https://planning.virginiabeach.gov/environment'],
    confidence: 'SOURCED',
    verifiedOn: R25,
    notes: 'Other environmental planner lines from the research: 757-385-8615, 757-385-8594. Planning main was also given as 757-385-4211. Named staff contacts live in cities.ts.',
  },
  {
    id: 'vb-ppr-tree-removal-form',
    city: 'Virginia Beach',
    topic: 'private_tree_cbpa',
    title: 'PPR Tree Removal form (RPA work)',
    rule:
      'RPA tree work is filed as a Preliminary Project Request (PPR) on the "Tree Removal Only" form, in Accela. One record per location — a duplicate PPR is voided.',
    whoToCall: { office: 'Planning Dept, Environmental Planning', phone: '757-385-6661' },
    form: { name: 'Preliminary Project Request – Tree Removal Only', url: 'https://planning.virginiabeach.gov/land-development' },
    fee: 'UNCONFIRMED — not found in sources',
    sourceUrls: ['https://planning.virginiabeach.gov/land-development', CITIES_TS_REF],
    confidence: 'SOURCED',
    verifiedOn: R25,
    notes: 'cities.ts calls it the "PPR Tree Removal Form", a.k.a. "Removal of Vegetation in a Resource Protection Area Application Form"; record # format YYYY-DSC-######. Fee and required contents UNCONFIRMED.',
  },
  {
    id: 'vb-rpa-mitigation',
    city: 'Virginia Beach',
    topic: 'private_tree_cbpa',
    title: 'RPA replacement planting',
    rule: 'Removals in the protected area typically require 3 replacement trees per tree removed (minimum 3), each at least 3.5 in. DBH at planting.',
    sourceUrls: [CITIES_TS_REF],
    confidence: 'SOURCED',
    verifiedOn: CITIES_TS,
  },
  {
    id: 'vb-rpa-dead-tree',
    city: 'Virginia Beach',
    topic: 'private_tree_cbpa',
    title: 'Dead or diseased trees in the RPA',
    rule:
      'No Virginia Beach rule was found for dead or diseased RPA trees. The general pattern elsewhere: removal still needs the administrator\'s approval, often with a certified-arborist letter, and replacement vegetation.',
    whoToCall: { office: 'Planning Dept, Environmental Planning', phone: '757-385-6661' },
    sourceUrls: ['https://register.dls.virginia.gov/details.aspx?id=10307'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: no VB-specific source; this is the general state and locality pattern only.',
  },
  {
    id: 'vb-cbpa-admin-variance',
    city: 'Virginia Beach',
    topic: 'private_tree_cbpa',
    title: 'CBPA administrative variance',
    rule: 'A denied or edge-case PPR can proceed through a CBPA administrative variance, with posted signs and a conditions letter.',
    fee: '$150 administrative variance fee (per 2026 correspondence)',
    sourceUrls: [CITIES_TS_REF],
    confidence: 'SOURCED',
    verifiedOn: CITIES_TS,
  },
  {
    id: 'vb-single-tree-by-email',
    city: 'Virginia Beach',
    topic: 'private_tree_cbpa',
    title: 'Simple single-tree cases',
    rule: 'Simple single-tree cases have been approved directly by the CBPA planner over email, with conditions. Ask the planner before assuming a full PPR.',
    whoToCall: { office: 'Planning Dept, Environmental Planning', phone: '757-385-6661' },
    sourceUrls: [CITIES_TS_REF],
    confidence: 'SOURCED',
    verifiedOn: CITIES_TS,
  },
  {
    id: 'vb-cbpa-board',
    city: 'Virginia Beach',
    topic: 'private_tree_cbpa',
    title: 'Chesapeake Bay Preservation Area Board',
    rule: 'Exceptions to the RPA rules go to the Chesapeake Bay Preservation Area Board.',
    sourceUrls: ['https://planning.virginiabeach.gov/boards-commissions/chesapeake-bay-board'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'vb-outside-overlay',
    city: 'Virginia Beach',
    topic: 'private_tree_cbpa',
    title: 'Private lots outside protected areas',
    rule:
      'No general city permit was found for removing a tree on a single-family lot outside the RPA, the right-of-way, and tree-preservation areas shown on approved site plans. Verify with the city.',
    sourceUrls: ['https://cityrulelookup.com/cities/virginia-beach-va/landscaping'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: third-party summary only, not confirmed on a city page.',
  },
  {
    id: 'vb-hazard-order',
    city: 'Virginia Beach',
    topic: 'hazard_order',
    title: 'Hazard tree orders (City Code § 23-50.1)',
    rule:
      'The code enforcement administrator or city arborist can order a dead, diseased or dangerous tree removed. If the owner does not act, the city has it done and charges the owner.',
    fee: 'Cost of the work plus a $150 admin fee, charged by the city if the owner does not act',
    leadTime: '7–30 days to comply, as set in the order',
    sourceUrls: ['http://virginiabeach.elaws.us/code/coor_ch23_arti_sec23-50.1'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'vb-wetlands-board',
    city: 'Virginia Beach',
    topic: 'wetlands',
    title: 'Wetlands Board',
    rule: 'The Virginia Beach Wetlands Board reviews use or alteration of tidal wetlands, dunes and beaches.',
    sourceUrls: ['https://planning.virginiabeach.gov/boards-commissions/wetlands-board'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'vb-street-trees',
    city: 'Virginia Beach',
    topic: 'street_tree_row',
    title: 'Street and public-property trees',
    rule: 'Parks & Recreation (Park & Landscape Services) maintains roadway trees and assesses and removes hazardous trees on public property.',
    whoToCall: { office: 'Parks & Recreation, Park & Landscape Services' },
    sourceUrls: [
      'https://parks.virginiabeach.gov/outdoors/park-landscape-services',
      'https://parks.virginiabeach.gov/outdoors/caring-for-our-parks/urban-forestry',
    ],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'vb-street-tree-private-work',
    city: 'Virginia Beach',
    topic: 'street_tree_row',
    title: 'Private work on a city street tree',
    rule:
      'The city may permit cutting or trimming of a street tree only when the work is fully justified in the public interest, done as the permit directs, under the city arborist or superintendent of landscape services.',
    whoToCall: { office: 'Parks & Recreation, Park & Landscape Services' },
    sourceUrls: ['http://vtod.frec.vt.edu/Documents/Virginia%20Beach.pdf'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: from a 2016 Virginia Tech code abstract; the current code section number was not confirmed.',
  },
  {
    id: 'vb-row-permit',
    city: 'Virginia Beach',
    topic: 'row_work_mot',
    title: 'Right-of-way permit',
    rule: 'A right-of-way permit is required for any activity within a City-owned right-of-way or easement. The Development Services Center issues it.',
    whoToCall: {
      office: 'Development Services Center',
      phone: '757-385-4621',
      address: 'Municipal Center Bldg 3, 2403 Courthouse Dr, Virginia Beach',
    },
    fee: 'UNCONFIRMED — not found in sources',
    leadTime: 'UNCONFIRMED — not found in sources',
    sourceUrls: ['https://planning.virginiabeach.gov/permits/right-of-way'],
    confidence: 'SOURCED',
    verifiedOn: R25,
    notes: 'Permit requirement is sourced; fee and lead time are UNCONFIRMED.',
  },
  {
    id: 'vb-row-resort-closure-ban',
    city: 'Virginia Beach',
    topic: 'row_work_mot',
    title: 'Oceanfront & Sandbridge closure ban, May 1 – Sep 30',
    rule: 'No sidewalk or lane closures at the Oceanfront or Sandbridge from May 1 to Sep 30 unless the Public Works Director grants a waiver.',
    whoToCall: { office: 'Development Services Center', phone: '757-385-4621' },
    sourceUrls: ['https://planning.virginiabeach.gov/permits/right-of-way'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'vb-historic',
    city: 'Virginia Beach',
    topic: 'historic',
    title: 'Historic Preservation Commission (advisory)',
    rule: 'The Historic Preservation Commission is advisory (created 2008). No historic-district tree review was found. Ask the city before tree work on a historic property.',
    sourceUrls: ['https://planning.virginiabeach.gov/boards-commissions/historic-preservation-commission'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: sources are silent on tree review; absence of a rule in a snippet is not evidence there is none.',
  },
  {
    id: 'vb-landfill-no-commercial-yard-waste',
    city: 'Virginia Beach',
    topic: 'disposal',
    title: 'City landfill refuses commercial yard waste',
    rule: 'The city Landfill & Resource Recovery Center accepts no commercial yard waste. Vehicles with commercial signage or work equipment are turned away.',
    whoToCall: { office: 'VB Landfill & Resource Recovery Center', address: '1989 Jake Sears Rd, Virginia Beach' },
    sourceUrls: ['https://pw.virginiabeach.gov/trash-recycling/landfill-and-rrc'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'vb-yard-debris-containers',
    city: 'Virginia Beach',
    topic: 'disposal',
    title: 'Contractors haul their own debris',
    rule: 'City yard-debris containers may not be used by contractors. Contractor-generated debris must be hauled by the contractor.',
    sourceUrls: ['https://pw.virginiabeach.gov/trash-recycling/curbside-services/yard-debris'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'vb-no-yard-debris-burning',
    city: 'Virginia Beach',
    topic: 'burning',
    title: 'Yard debris may not be burned',
    rule: 'Leaves, limbs and yard debris are not approved for open burning in Virginia Beach.',
    sourceUrls: ['https://fire.virginiabeach.gov/fire-prevention/fire-regulations/open-burning-recreational-fires'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'vb-eagle-dwr',
    city: 'Virginia Beach',
    topic: 'eagle_wildlife',
    title: 'Eagle nests: DWR coordination first',
    rule: 'Trees near an eagle\'s nest require coordination with the Virginia Department of Wildlife Resources (DWR) before the city issues CBPA approval.',
    whoToCall: { office: 'Virginia Department of Wildlife Resources' },
    sourceUrls: [CITIES_TS_REF, 'https://dwr.virginia.gov'],
    confidence: 'SOURCED',
    verifiedOn: CITIES_TS,
    notes: 'Learned from a VB case in mined correspondence. DWR is a state agency, so it likely applies in the other cities too — UNCONFIRMED there.',
  },
];

// ── Norfolk ─────────────────────────────────────────────────────────────────

const NORFOLK: Fact[] = [
  {
    id: 'nor-cbpa-prune-too',
    city: 'Norfolk',
    topic: 'private_tree_cbpa',
    title: 'CBPA permit covers pruning too',
    rule:
      'In the RPA or Intensely Developed Area (IDA) of the CBPA Overlay District it is unlawful to plant, transplant, trim, prune, remove or otherwise disturb any tree, shrub or other vegetation without a permit. All trees and shrubs within the 100-ft CBPA buffer are protected. This covers pruning, which is stricter than the other cities.',
    form: {
      name: 'CBPA Tree and Shrub Information / CBPA Tree Permit',
      url: 'https://www.norfolk.gov/DocumentCenter/View/65912/Chesapeake-Bay-Preservation-Area-Tree-and-Shrub-information',
    },
    sourceUrls: [
      'https://www.norfolk.gov/DocumentCenter/View/65912/Chesapeake-Bay-Preservation-Area-Tree-and-Shrub-information',
      'https://www.norfolk.gov/Faq.aspx?QID=666',
    ],
    confidence: 'SOURCED',
    verifiedOn: R25,
    notes: 'Phone for Environmental Services is in conflict — see nor-cbpa-phone-conflict. Named staff contacts live in cities.ts.',
  },
  {
    id: 'nor-cbpa-review',
    city: 'Norfolk',
    topic: 'private_tree_cbpa',
    title: 'Who reviews CBPA tree work',
    rule:
      'Environmental Services (CBPA) reviews tree work in the overlay. Check the parcel on air.norfolk.gov: green checker = RPA, red checker = IDA; the same map shows the Coastal Resilience Overlay.',
    whoToCall: { office: 'Environmental Services (CBPA)' },
    sourceUrls: ['https://www.norfolk.gov/2752/Environmental-Services', CITIES_TS_REF],
    confidence: 'SOURCED',
    verifiedOn: R25,
    notes: 'Phone deliberately omitted — see nor-cbpa-phone-conflict.',
  },
  {
    id: 'nor-cbpa-phone-conflict',
    city: 'Norfolk',
    topic: 'private_tree_cbpa',
    title: 'Environmental Services phone: two numbers on record',
    rule: 'Two numbers are on record for Norfolk CBPA questions and it is not known which is current. Dial and confirm before using either.',
    whoToCall: { office: 'Environmental Services (CBPA)', phone: '757-664-4368 or 757-664-4752 (conflict — confirm which is current)' },
    sourceUrls: [
      'https://www.norfolk.gov/DocumentCenter/View/65912/Chesapeake-Bay-Preservation-Area-Tree-and-Shrub-information',
      CITIES_TS_REF,
    ],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes:
      'UNCONFIRMED: the CBPA document snippet gives 757-664-4368 (Environmental Services); cities.ts lists Environmental Services at 757-664-4752, which a research snippet labels Planning. cities.ts also lists the Environmental Service Manager at 757-664-4363 — one digit off 4368, so one may be a transcription slip. Not picked; dial all before use.',
  },
  {
    id: 'nor-specimen-mitigation',
    city: 'Norfolk',
    topic: 'private_tree_cbpa',
    title: 'Mitigation; 36-in. DBH specimen trees',
    rule:
      'Mitigation is set by size class, species and location. Trees 36 in. DBH or larger are "large specimen" trees, and their mitigation depends on a risk assessment by an ISA Certified Arborist.',
    sourceUrls: ['https://norfolk.gov/DocumentCenter/View/23107/Norfolk-tree-mitigation-standards-2015'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'nor-rpa-mitigation-ratio',
    city: 'Norfolk',
    topic: 'private_tree_cbpa',
    title: 'RPA replacement ratio',
    rule: 'RPA removals are expected to be replaced about 3-to-1 (minimum 3, each at least 3.5 in. DBH). Confirm the current ratio with Environmental Services.',
    sourceUrls: [CITIES_TS_REF],
    confidence: 'SOURCED',
    verifiedOn: CITIES_TS,
  },
  {
    id: 'nor-outside-cbpa',
    city: 'Norfolk',
    topic: 'private_tree_cbpa',
    title: 'Private trees outside the CBPA',
    rule: 'No general private-tree permit was found for Norfolk outside the CBPA overlay. Verify with the city.',
    sourceUrls: ['https://www.norfolk.gov/2752/Environmental-Services'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: sources are silent; not found is not the same as none.',
  },
  {
    id: 'nor-street-tree-permit',
    city: 'Norfolk',
    topic: 'street_tree_row',
    title: 'Tree Permit Application for city trees',
    rule:
      'Planting, pruning, trimming or removing a tree on city property needs a Tree Permit Application — even work "in close proximity to any city tree". This is separate from the CBPA permit. Right-of-way trees go to the City Forester.',
    whoToCall: { office: 'Parks & Urban Forestry', email: 'treepermits@norfolk.gov', address: '2839 Dana St, Norfolk' },
    form: { name: 'Tree Permit Application (street trees)', url: 'https://norfolk.gov/DocumentCenter/View/917/Tree-Street-Application' },
    sourceUrls: ['https://norfolk.gov/DocumentCenter/View/917/Tree-Street-Application', 'https://www.norfolk.gov/5457/Urban-Forestry'],
    confidence: 'SOURCED',
    verifiedOn: R25,
    notes: 'Urban Forestry phone 757-823-4023 may be out of date (UNCONFIRMED) — use the email.',
  },
  {
    id: 'nor-crape-myrtle-suckers',
    city: 'Norfolk',
    topic: 'street_tree_row',
    title: 'Resident-only carve-out: crape-myrtle suckers',
    rule:
      'The city lets residents prune crape-myrtle base suckers under 1 in. in the strip beside their own property. It is a resident carve-out only; contractor work on a city tree still goes through the Tree Permit Application.',
    sourceUrls: ['https://norfolk.gov/DocumentCenter/View/917/Tree-Street-Application'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'nor-row-closure-permit',
    city: 'Norfolk',
    topic: 'row_work_mot',
    title: 'Street, lane and sidewalk closure permits',
    rule:
      'Right-of-Way Management issues temporary street, lane and sidewalk closure permits. Submit the application, plans and a traffic control (maintenance of traffic, MOT) plan. Work follows the ROW Excavation & Restoration Manual and the Virginia Work Area Protection Manual.',
    whoToCall: { office: 'Right-of-Way Management Division, permits office', phone: '757-664-7306' },
    fee: '$25 non-refundable application fee on closure and ROW permits, from July 1, 2026',
    leadTime: 'Submit application, plans and MOT 7–14 days ahead',
    sourceUrls: ['https://norfolk.gov/345/Right-of-Way-Management', 'https://www.norfolk.gov/4543/Permits-Fees'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'nor-historic-coa',
    city: 'Norfolk',
    topic: 'historic',
    title: 'Architectural Review Board (COA)',
    rule:
      'The Architectural Review Board issues Certificates of Appropriateness (COAs) for exterior changes in local historic districts; a General COA covers minor alterations including landscaping. Whether removing a private tree in a district needs a COA is not confirmed — ask before starting.',
    whoToCall: { office: 'Architectural Review Board' },
    sourceUrls: ['https://www.norfolk.gov/1090/Architectural-Review-Board', 'https://norfolk.gov/DocumentCenter/View/21150/Historic-Districts-Brochure-COA'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: private-tree COA coverage was an inference in the snippet, not a stated rule.',
  },
  {
    id: 'nor-yard-waste',
    city: 'Norfolk',
    topic: 'disposal',
    title: 'Contractors remove their own yard waste',
    rule: 'Lawn services and contractors are responsible for removing the yard waste they generate.',
    sourceUrls: ['https://norfolk.gov/402/Yard-Waste-Recycling'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'nor-burning',
    city: 'Norfolk',
    topic: 'burning',
    title: 'Open burning rules not found',
    rule: 'Norfolk\'s open-burning rules for yard debris were not found. Ask the Fire Marshal before any burning.',
    whoToCall: { office: 'Norfolk Fire Marshal' },
    sourceUrls: ['https://www.dof.virginia.gov/wildland-prescribed-fire/fire-laws/4-pm-burning-law/'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: no Norfolk source; only the state 4 PM law is cited.',
  },
];

// ── Chesapeake ──────────────────────────────────────────────────────────────

const CHESAPEAKE_CBPA_URL = 'https://www.cityofchesapeake.net/548/Chesapeake-Bay-Preservation-Area-CBPA';

const CHESAPEAKE: Fact[] = [
  {
    id: 'ches-rpa-canopy',
    city: 'Chesapeake',
    topic: 'private_tree_cbpa',
    title: 'RPA: 100-ft woody buffer, 50% canopy',
    rule:
      'The RPA must keep a 100-ft woody buffer with at least 50% canopy. Vegetation removal is allowed only under an approved buffer-modification plan: sight lines, access paths, woodlot management, best management practices (BMPs) and shoreline projects.',
    whoToCall: { office: 'Development & Permits', phone: '757-382-6018' },
    sourceUrls: [
      'https://library.municode.com/va/chesapeake/codes/code_of_ordinances?nodeId=PTIICOOR_CH26EN_ARTIXCHBAPRARDI',
      CHESAPEAKE_CBPA_URL,
    ],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'ches-dead-tree-discretion',
    city: 'Chesapeake',
    topic: 'private_tree_cbpa',
    title: 'Dead or storm-weakened trees: Director\'s discretion',
    rule: 'Dead trees, or trees weakened by age, storm or fire, may be excluded at the discretion of the Director of Development & Permits. Ask before cutting.',
    whoToCall: { office: 'Development & Permits', phone: '757-382-6018' },
    sourceUrls: [
      'https://library.municode.com/va/chesapeake/codes/code_of_ordinances?nodeId=PTIICOOR_CH26EN_ARTIXCHBAPRARDI',
      CHESAPEAKE_CBPA_URL,
    ],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'ches-cbpa-submittal',
    city: 'Chesapeake',
    topic: 'private_tree_cbpa',
    title: 'CBPA/RPA submittal (eBUILD)',
    rule:
      'File through the eBUILD portal with the street address or tax parcel number, a site plan showing the RPA buffer, and photos of the trees to be removed. Expect replacement planting of about 3-to-1.',
    whoToCall: { office: 'Development & Permits', phone: '757-382-6018' },
    form: { name: 'CBPA/RPA submittal (eBUILD)' },
    sourceUrls: [CITIES_TS_REF],
    confidence: 'SOURCED',
    verifiedOn: CITIES_TS,
  },
  {
    id: 'ches-scale-tiers',
    city: 'Chesapeake',
    topic: 'private_tree_cbpa',
    title: 'Tree count drives the review path',
    rule: 'Roughly 3–9 trees may trigger a staff site visit. 10 or more mature trees need a full CBPA Exception with mitigation and a CBPA Board public hearing, with advertising paid by the applicant.',
    sourceUrls: [CITIES_TS_REF],
    confidence: 'SOURCED',
    verifiedOn: CITIES_TS,
  },
  {
    id: 'ches-exception-hearing',
    city: 'Chesapeake',
    topic: 'private_tree_cbpa',
    title: 'CBPA Exception and Board hearing',
    rule: 'RPA work the ordinance does not allow needs a CBPA Exception application, followed by a CBPA Board hearing.',
    whoToCall: { office: 'Development & Permits', phone: '757-382-6018' },
    form: {
      name: 'CBPA Exception Application',
      url: 'https://www.cityofchesapeake.net/DocumentCenter/View/16222/CBPA-Exception-Application-Instructions-PDF',
    },
    leadTime: 'Board hearing 40–45 days after filing',
    sourceUrls: ['https://www.cityofchesapeake.net/DocumentCenter/View/16222/CBPA-Exception-Application-Instructions-PDF', CITIES_TS_REF],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'ches-2025-manual',
    city: 'Chesapeake',
    topic: 'private_tree_cbpa',
    title: '2025 CBPA ordinance update and manual',
    rule: 'The CBPA ordinance was amended in 2025. Use the Specifications Manual dated 11/05/2025, not an older copy.',
    form: {
      name: 'CBPA Specifications Manual (2025)',
      url: 'https://www.cityofchesapeake.net/DocumentCenter/View/29520/CBPA-Specifications-Manual-2025-PDF',
    },
    sourceUrls: ['https://www.cityofchesapeake.net/DocumentCenter/View/29520/CBPA-Specifications-Manual-2025-PDF'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'ches-site-plan-trees',
    city: 'Chesapeake',
    topic: 'private_tree_cbpa',
    title: 'Tree preservation on site plans',
    rule: 'Trees shown for preservation on a site plan fall under the Landscape & Tree Preservation Ordinance.',
    sourceUrls: ['https://www.cityofchesapeake.net/400/Landscape-Tree-Preservation'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'ches-city-tree-policy',
    city: 'Chesapeake',
    topic: 'street_tree_row',
    title: 'City Tree Removal Policy',
    rule:
      'Urban Forestry removes dead, leaning or diseased city trees — not private trees, and not city-tree limbs overhanging private property. Removal by the adjacent owner, at the owner\'s expense with proper right-of-way permits, is case by case and needs Public Works Director approval.',
    whoToCall: { office: 'Urban Forestry Division (Parks, Recreation & Tourism)', phone: '757-382-2489' },
    sourceUrls: ['https://www.cityofchesapeake.net/1007/City-of-Chesapeake-Tree-Removal-Policy', 'https://www.cityofchesapeake.net/3693/Urban-Forestry'],
    confidence: 'SOURCED',
    verifiedOn: R25,
    notes: 'Phone is 757-382-CITY.',
  },
  {
    id: 'ches-row-permits',
    city: 'Chesapeake',
    topic: 'row_work_mot',
    title: 'Right-of-way permits (Civil Permits)',
    rule: 'The Civil Permits Section issues right-of-way and miscellaneous right-of-way permits. Bond and inspection fees are scoped to the plan.',
    whoToCall: { office: 'Civil Permits Section', phone: '757-382-8298' },
    fee: 'UNCONFIRMED — bond and inspection fees are scoped to the plan',
    leadTime: 'UNCONFIRMED — not found in sources',
    sourceUrls: ['https://www.cityofchesapeake.net/448/Civil-Permits', 'https://www.cityofchesapeake.net/1008/Permits-Bonds-Right-of-Way'],
    confidence: 'SOURCED',
    verifiedOn: R25,
    notes: 'Permit requirement is sourced; fee and lead time are UNCONFIRMED.',
  },
  {
    id: 'ches-historic',
    city: 'Chesapeake',
    topic: 'historic',
    title: 'South Norfolk historic district (BHAR)',
    rule: 'The Board of Historic & Architectural Review covers significant exterior changes visible from the street in the South Norfolk district. Whether tree work is covered is not confirmed — ask before starting.',
    whoToCall: { office: 'Board of Historic & Architectural Review' },
    sourceUrls: ['https://www.cityofchesapeake.net/1244/Chesapeake-Board-of-Historic-Architectur'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: tree coverage not stated in sources.',
  },
  {
    id: 'ches-yard-waste',
    city: 'Chesapeake',
    topic: 'disposal',
    title: 'No city contractor drop-off found',
    rule: 'No city drop-off for contractor yard waste was found in Chesapeake. Plan a regional or private site and call ahead.',
    sourceUrls: ['https://www.spsava.gov/162/Residential-Waste-Disposal-Guidelines'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: no Chesapeake source; SPSA cited as the regional fallback.',
  },
  {
    id: 'ches-burn-permit',
    city: 'Chesapeake',
    topic: 'burning',
    title: 'Fire Marshal burn permit',
    rule: 'Land-clearing and commercial burning need an operational permit from the Fire Marshal.',
    whoToCall: { office: 'Chesapeake Fire Marshal' },
    sourceUrls: ['https://www.cityofchesapeake.net/3402/Regulations-for-Open-Burning'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
];

// ── Portsmouth ──────────────────────────────────────────────────────────────

const PORTSMOUTH_CBPA_URL = 'https://www.portsmouthva.gov/chesapeake-bay-program';

const PORTSMOUTH: Fact[] = [
  {
    id: 'pts-cbpa-overlay',
    city: 'Portsmouth',
    topic: 'private_tree_cbpa',
    title: 'CBPA Overlay (Code Chapter 9.1)',
    rule:
      'The city manager\'s designee may allow RPA vegetation removal only for sight lines, paths, woodlot management and BMPs. Mature trees are to be pruned instead of removed, and removed trees must be replaced to 50% canopy.',
    whoToCall: { office: 'Planning (Chesapeake Bay Program)', phone: '757-393-8836' },
    sourceUrls: [
      'https://library.municode.com/va/portsmouth/codes/code_of_ordinances?nodeId=PTIICO_CH9.1CHBAPRAROVDI',
      PORTSMOUTH_CBPA_URL,
    ],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'pts-wqia',
    city: 'Portsmouth',
    topic: 'private_tree_cbpa',
    title: 'Water Quality Impact Assessment (WQIA)',
    rule:
      'A WQIA is required for all land disturbance in the RPA. The plan shows the 100-ft RPA buffer (50-ft seaward and landward lines), structures, limits of land disturbance, and each tree\'s location, species and caliper.',
    whoToCall: { office: 'Planning (Chesapeake Bay Program)', phone: '757-393-8836' },
    form: { name: 'Water Quality Impact Assessment (WQIA)' },
    sourceUrls: [PORTSMOUTH_CBPA_URL, CITIES_TS_REF],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'pts-exception',
    city: 'Portsmouth',
    topic: 'private_tree_cbpa',
    title: 'Chesapeake Bay Exception Application',
    rule: 'RPA work outside what the overlay allows needs a Chesapeake Bay Exception application, filed with Planning.',
    whoToCall: { office: 'Planning (Chesapeake Bay Program)', phone: '757-393-8836' },
    form: { name: 'Chesapeake Bay Exception Application' },
    sourceUrls: [PORTSMOUTH_CBPA_URL, CITIES_TS_REF],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'pts-rpa-mitigation',
    city: 'Portsmouth',
    topic: 'private_tree_cbpa',
    title: 'Replacement planting set in WQIA review',
    rule: 'Staff set the required replacement vegetation during WQIA review; expect about 3-to-1 (minimum 3, each at least 3.5 in. DBH).',
    sourceUrls: [CITIES_TS_REF],
    confidence: 'SOURCED',
    verifiedOn: CITIES_TS,
  },
  {
    id: 'pts-dead-tree',
    city: 'Portsmouth',
    topic: 'private_tree_cbpa',
    title: 'Dead or diseased RPA trees',
    rule: 'Dead or diseased RPA trees may be removed if certified by a forester or arborist. Confirm the exact requirement with Planning.',
    whoToCall: { office: 'Planning (Chesapeake Bay Program)', phone: '757-393-8836' },
    sourceUrls: ['https://library.municode.com/va/portsmouth/codes/code_of_ordinances?nodeId=PTIICO_CH9.1CHBAPRAROVDI'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: the snippet did not confirm the exact wording.',
  },
  {
    id: 'pts-outside-cbpa',
    city: 'Portsmouth',
    topic: 'private_tree_cbpa',
    title: 'Private trees outside the CBPA',
    rule: 'No general private-tree permit was found for Portsmouth outside the CBPA overlay. Verify with the city.',
    sourceUrls: [PORTSMOUTH_CBPA_URL],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: sources are silent; not found is not the same as none.',
  },
  {
    id: 'pts-street-trees',
    city: 'Portsmouth',
    topic: 'street_tree_row',
    title: 'Street trees',
    rule: 'Planting on city property needs the director\'s permit. The rule for pruning or removing street trees, and which department owns it, is not confirmed — ask before touching a city tree.',
    sourceUrls: ['http://vtod.frec.vt.edu/Documents/Portsmouth.pdf'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: 2016 Virginia Tech abstract covers planting only.',
  },
  {
    id: 'pts-row-use-permit',
    city: 'Portsmouth',
    topic: 'row_work_mot',
    title: 'Right-of-Way Use Permit (bond required)',
    rule:
      'Work in the right-of-way needs a ROW Use Permit through the City Engineer. It requires a bond (City Code § 32-59) and a traffic control plan under the Virginia Work Area Protection Manual, reviewed by Engineering & Technical Services.',
    whoToCall: { office: 'Engineering & Technical Services', phone: '757-393-8592' },
    form: {
      name: 'Application for Work in the Right-of-Way',
      url: 'https://www.portsmouthva.gov/DocumentCenter/View/6084/Application-for-Work-in-the-Right-of-Way',
    },
    fee: 'UNCONFIRMED — work-permit fee not found',
    leadTime: 'UNCONFIRMED — not found in sources',
    sourceUrls: [
      'https://www.portsmouthva.gov/800/Right-of-Way-Use-Permits',
      'https://www.portsmouthva.gov/DocumentCenter/View/9050/Right-of-Way-Policy',
    ],
    confidence: 'SOURCED',
    verifiedOn: R25,
    notes: 'The closure fees found in research are for special events only and do not apply to work permits.',
  },
  {
    id: 'pts-pops',
    city: 'Portsmouth',
    topic: 'row_work_mot',
    title: 'POPS online permit system',
    rule: 'Portsmouth right-of-way permits run through the POPS online system.',
    form: { name: 'POPS', url: 'https://www2.portsmouthva.gov/tm_web/' },
    sourceUrls: ['https://www2.portsmouthva.gov/tm_web/'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'pts-historic-coa',
    city: 'Portsmouth',
    topic: 'historic',
    title: 'Historic Preservation Commission COA',
    rule:
      'A Certificate of Appropriateness (COA) is required before any material change in appearance to the exterior of a building, structure, or lot in Olde Towne and the other historic districts. Whether "or lot" covers tree removal is not confirmed — ask before starting.',
    whoToCall: { office: 'Historic Preservation Commission' },
    form: { name: 'Olde Towne Historic District Design Guidelines', url: 'https://www.portsmouthva.gov/422/Olde-Towne-Historic-District-Design-Guid' },
    sourceUrls: ['https://www.portsmouthva.gov/182/Historic-Preservation-Commission', 'https://www.portsmouthva.gov/422/Olde-Towne-Historic-District-Design-Guid'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: "or lot" plausibly covers tree removal; no source says so.',
  },
  {
    id: 'pts-yard-waste',
    city: 'Portsmouth',
    topic: 'disposal',
    title: 'No city contractor drop-off found',
    rule: 'No city drop-off for contractor yard waste was found in Portsmouth. Plan a regional or private site and call ahead.',
    sourceUrls: ['https://www.spsava.gov/162/Residential-Waste-Disposal-Guidelines'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: no Portsmouth source; SPSA cited as the regional fallback.',
  },
  {
    id: 'pts-burning',
    city: 'Portsmouth',
    topic: 'burning',
    title: 'Open burning rules not found',
    rule: 'Portsmouth\'s open-burning rules for yard debris were not found. Ask the Fire Marshal before any burning.',
    whoToCall: { office: 'Portsmouth Fire Marshal' },
    sourceUrls: ['https://www.dof.virginia.gov/wildland-prescribed-fire/fire-laws/4-pm-burning-law/'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: no Portsmouth source; only the state 4 PM law is cited.',
  },
];

// ── Regional (Hampton Roads) ────────────────────────────────────────────────

const REGIONAL: Fact[] = [
  {
    id: 'reg-spsa-yard-waste',
    city: 'Regional',
    topic: 'disposal',
    title: 'SPSA transfer stations: yard-waste limits',
    rule:
      'SPSA transfer stations take yard waste. Loose material must be bagged, and limbs must be under 6 ft long and under 6 in. in diameter. Box trucks and cargo vans pay the commercial tipping fee.',
    whoToCall: { office: 'SPSA (Southeastern Public Service Authority)' },
    fee: 'Commercial tipping fee for box trucks and cargo vans; per-ton rate UNCONFIRMED',
    sourceUrls: ['https://www.spsava.gov/162/Residential-Waste-Disposal-Guidelines', 'https://www.spsava.gov/35/Acceptable-Materials'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'reg-spsa-landfill',
    city: 'Regional',
    topic: 'disposal',
    title: 'SPSA Regional Landfill',
    rule: 'Call the SPSA Regional Landfill before hauling there; whether it takes green waste at the landfill face is not confirmed.',
    whoToCall: { office: 'SPSA Regional Landfill', phone: '757-961-3683' },
    sourceUrls: ['https://www.spsava.gov/193/Regional-Landfill'],
    confidence: 'SOURCED',
    verifiedOn: R25,
    notes: 'INTERNAL: the Regional Landfill is physically in Suffolk. Never name that city to a customer (R1, §12 forbidden-strings). Green waste at the landfill face is UNCONFIRMED.',
  },
  {
    id: 'reg-hr-recovery-center',
    city: 'Regional',
    topic: 'disposal',
    title: 'Hampton Roads Recovery Center (private)',
    rule: 'A private disposal option. Whether it accepts green waste is not confirmed — call first.',
    whoToCall: { office: 'Hampton Roads Recovery Center', phone: '757-420-0128', address: '1613 Centerville Tpk' },
    sourceUrls: ['https://www.wasteconnections.com/hampton-roads-recovery-center'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: green-waste acceptance not stated. Research listed it under Virginia Beach options; filed as Regional because it serves the area, not one city.',
  },
  {
    id: 'reg-wetlands-jpa',
    city: 'Regional',
    topic: 'wetlands',
    title: 'Tidal wetlands: Joint Permit Application',
    rule:
      'Tidal-wetland work goes through the Joint Permit Application (JPA) to the Virginia Marine Resources Commission (VMRC), with the local wetlands board, DEQ and the Army Corps reviewing.',
    whoToCall: { office: 'Virginia Marine Resources Commission (VMRC)' },
    form: { name: 'Joint Permit Application (JPA)', url: 'https://www.mrc.virginia.gov/regulations/hm-permits.shtm' },
    sourceUrls: ['https://www.vims.edu/ccrm/advisory/ccrmp/handbook/permits/', 'https://www.mrc.virginia.gov/regulations/hm-permits.shtm'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
];

// ── Virginia (state law, utilities, licensing) ──────────────────────────────

const VIRGINIA: Fact[] = [
  {
    id: 'va-811-notice',
    city: 'Virginia',
    topic: 'utility_811',
    title: 'VA811 notice before digging',
    rule:
      'No excavation without notifying VA811 first — at least 2 working days ahead. Operators have 48 hours from 7:00 a.m. the next working day to mark. A ticket is valid 15 working days; request re-marks 3 working days before it expires.',
    whoToCall: { office: 'VA811 (Miss Utility)', phone: '811' },
    leadTime: '2 working days minimum; ticket valid 15 working days',
    sourceUrls: ['https://law.lis.virginia.gov/vacode/title56/chapter10.3/section56-265.17/'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'va-811-stump',
    city: 'Virginia',
    topic: 'utility_811',
    title: 'Stump grinding needs a VA811 ticket',
    rule: 'VA811 counts removing a stump as digging, and "stump grinding or removal" is a ticket work type. Treat every stump grind as needing a ticket.',
    whoToCall: { office: 'VA811 (Miss Utility)', phone: '811' },
    leadTime: '2 working days minimum',
    sourceUrls: ['https://va811.com/excavators/damage-prevention-act-2/', 'https://va811.com/wp-content/uploads/2019/08/work-type-list.pdf'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'va-dominion-10ft',
    city: 'Virginia',
    topic: 'power_lines',
    title: 'Dominion Energy: 10-ft rule',
    rule:
      'Only qualified utility line-clearance contractors may work within 10 ft of power lines, or on a tree with branches within 10 ft. Dominion does not trim around service drops but will temporarily disconnect the drop so a contractor can work.',
    whoToCall: { office: 'Dominion Energy', phone: '1-866-366-4357' },
    sourceUrls: ['https://www.dominionenergy.com/safety/electric-safety/tree-trimming-and-powerlines/va-tree-trimming-and-powerlines'],
    confidence: 'SOURCED',
    verifiedOn: R25,
    notes: 'Dominion publishes it as 1-866-DOM-HELP.',
  },
  {
    id: 'va-high-voltage-act',
    city: 'Virginia',
    topic: 'power_lines',
    title: 'Overhead High Voltage Line Safety Act',
    rule:
      'No work within 10 ft of lines at 600 V or more without safety arrangements made with the utility (Va. Code § 59.1-406 et seq.). Notice goes to the utility under § 59.1-411. Violators indemnify the utility.',
    whoToCall: { office: 'Dominion Energy', phone: '1-866-366-4357' },
    leadTime: 'Utility must start arrangements within 5 working days of notice',
    sourceUrls: ['https://law.lis.virginia.gov/vacodefull/title59.1/chapter30/', 'https://doli.virginia.gov/wp-content/uploads/2023/12/Program-Directive-12246A.pdf'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'va-approach-distances',
    city: 'Virginia',
    topic: 'power_lines',
    title: 'OSHA / ANSI Z133 approach distances',
    rule: 'Qualified line-clearance arborists work under OSHA 1910.269 minimum approach distances. Everyone else keeps 10 ft from lines up to 50 kV, and more at higher voltages.',
    sourceUrls: [
      'https://tcimag.tcia.org/safety/part-5-work-practices-near-utility-conductors-different-categories-of-tree-workers/',
      'https://tcimag.tcia.org/safety/incidental-line-clearance-what-arborists-need-to-know/',
    ],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'va-z133-2026',
    city: 'Virginia',
    topic: 'power_lines',
    title: 'ANSI Z133-2026 electrical qualification levels',
    rule: 'The ANSI Z133-2026 revision restructures Section 4: "incidental line clearance" becomes "Level 2 Arborist – Electrically Qualified". Final publication status is not confirmed.',
    sourceUrls: ['https://tcimag.tcia.org/training/ansi-z133-2026-the-progression-of-electrical-qualifications/'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: the trade magazine calls the revision "pending".',
  },
  {
    id: 'va-dpor-classes',
    city: 'Virginia',
    topic: 'licensing',
    title: 'DPOR contractor license classes',
    rule: 'Virginia contractor license class is set by the value of a single project: Class C, B or A, effective July 1, 2025. Thresholds are in the fee line.',
    whoToCall: { office: 'Virginia DPOR, Board for Contractors' },
    fee: 'Class C: over $1,000 and under $30,000 per project · Class B: $30,000 to under $150,000 · Class A: $150,000 and up',
    sourceUrls: [
      'https://www.dpor.virginia.gov/sites/default/files/boards/Contractors/Contractor_Consumer_Info.pdf',
      'https://www.dpor.virginia.gov/News/AgencyLegislation2025',
    ],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
  {
    id: 'va-dpor-tree-work',
    city: 'Virginia',
    topic: 'licensing',
    title: 'Does tree work need a DPOR license?',
    rule: 'Whether tree trimming alone falls under DPOR contractor licensing is not confirmed. Third-party sites say stump grinding and land disturbance are covered. Ask DPOR.',
    whoToCall: { office: 'Virginia DPOR, Board for Contractors' },
    sourceUrls: ['https://contractorlicenserequirements.com/virginia/landscaping-license-requirements/'],
    confidence: 'UNCONFIRMED',
    verifiedOn: R25,
    notes: 'UNCONFIRMED: third-party source only, not DPOR.',
  },
  {
    id: 'va-4pm-burn-law',
    city: 'Virginia',
    topic: 'burning',
    title: '4 PM burning law, Feb 15 – Apr 30',
    rule: 'From Feb 15 to Apr 30, no open burning before 4 p.m. within 300 ft of woods or dry grass. Burning is allowed from 4 p.m. to midnight.',
    whoToCall: { office: 'Virginia Department of Forestry' },
    fee: 'Fine up to $500 plus fire-suppression costs',
    sourceUrls: ['https://www.dof.virginia.gov/wildland-prescribed-fire/fire-laws/4-pm-burning-law/'],
    confidence: 'SOURCED',
    verifiedOn: R25,
  },
];

export const FACTS: readonly Fact[] = [...VIRGINIA_BEACH, ...NORFOLK, ...CHESAPEAKE, ...PORTSMOUTH, ...REGIONAL, ...VIRGINIA];
